### PR TITLE
Hardfork Schedule Aggregation

### PR DESCRIPTION
**Pull request by mandrigin**
## Description

**NB!** As it currently is this PR is **backward incompatible** with the existing DB schema. The reason is that the current DB schema stores `next_fork_epoch` as `int64` and that doesn't allow to store peers with epoch not set (like `0xFFF...F`) because it overflows `int64`. This PR changes it to store as hex string instead.

Add a new aggregation `aggregateByHardforkSchedule` that shows which versions of hardforks are scheduled when in the crawled eth2 nodes

Example result:
```
{
  "data": {
    "aggregateByHardforkSchedule": [
      {
        "version": "0x01000000",
        "epoch": "18446744073709551615",
        "count": 7
      },
      {
        "version": "0x02001020",
        "epoch": "18446744073709551615",
        "count": 5
      },
      {
        "version": "0x70000071",
        "epoch": "18446744073709551615",
        "count": 2
      },
      {
        "version": "0x02000000",
        "epoch": "18446744073709551615",
        "count": 1
      },
      {
        "version": "0x62000071",
        "epoch": "18446744073709551615",
        "count": 1
      },
      {
        "version": "0x00000000",
        "epoch": "18446744073709551615",
        "count": 1
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by sadiq1971** [comment]
@mandrigin Thanks for the PR. Looks good and useful. However, it's failing on `go mod download`.  I can see the following error on the GitHub action.
```
Error: ../../../go/pkg/mod/github.com/vektah/gqlparser/v2@v2.4.6/validator/prelude.go:4:2: package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/embed)
make: *** [Makefile:34: test] Error 1
```

**Comment by mandrigin** [comment]
> @mandrigin Thanks for the PR. Looks good and useful. However, it's failing on `go mod download`. I can see the following error on the GitHub action.
> 
> ```
> Error: ../../../go/pkg/mod/github.com/vektah/gqlparser/v2@v2.4.6/validator/prelude.go:4:2: package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/embed)
> make: *** [Makefile:34: test] Error 1
> ```

oh, go 1.15? that is a bit of a vintage version you have there :) can't reproduce locally with `1.18`.
I will try to change the version in GH actions...

**Comment by mandrigin** [comment]
updated the golangci version too

**Comment by mandrigin** [comment]
@sadiq1971 can you allow the CI run now?

**Comment by sadiq1971** [comment]
> @sadiq1971 can you allow the CI run now?

We have updated the go version for this project in recent pr. Can you please accept the changes while resolving conflicts?

**Comment by mandrigin** [comment]
@sadiq1971 done

**Comment by mandrigin** [comment]
@sadiq1971 ping :)

**Comment by sadiq1971** [comment]
> @sadiq1971 ping :)

Need to run `go mod download`

**Comment by mandrigin** [comment]
@sadiq1971 done

**Comment by sadiq1971** [comment]
> @sadiq1971 done

Fix the lint

**Comment by mandrigin** [comment]
@sadiq1971 fixed the lint

**Review by sadiq1971 — APPROVED** [review]

**Comment by mandrigin** [comment]
@sadiq1971 awesome! is there anything I need to do to have it merged?

**Comment by sadiq1971** [comment]
> esome! is there anything I need to do to ha

No please feel free to merge

**Comment by mandrigin** [comment]
@sadiq1971 I can’t merge it, don’t have permissions :)

**Comment by sadiq1971** [comment]
> @sadiq1971 I can’t merge it, don’t have permissions :)

I will.

**Comment by mandrigin** [comment]
Thanks so much!

**Pull request merged**
