### PR TITLE
Bump to go 1.17

### PR DESCRIPTION
**Pull request by ansermino**
## Description

Bumps Go to v1.17.

## Changes

- Specify new go version
  - Update usage of `io/ioutil` & `os`
- Upgrade linter 
- Fix potential slow loris attack by adding `read_header_timeout` to server config.

### CODE REVIEW

**Comment by sadiq1971** [comment]
@ansermino, I don't see any significant code changes other than version upgrades. The crawler is not crawling nodes info for this branch and I don't see any logs as well. I will try to find out the core reason behind this.

**Comment by ansermino** [comment]
> @ansermino, I don't see any significant code changes other than version upgrades. The crawler is not crawling nodes info for this branch and I don't see any logs as well. I will try to find out the core reason behind this.

@sadiq1971 Good catch. Seems to only be discovering itself. Will try to remove the changes to Libp2p and see if that fixes it.

**Comment by ansermino** [comment]
@sadiq1971 Reduced the changes. Seems to work on my end, please confirm.

**Review by sadiq1971 — APPROVED** [review]

**Comment by sadiq1971** [comment]
> @sadiq1971 Reduced the changes. Seems to work on my end, please confirm.

Working on my end as well. Good to go.

**Pull request merged**
